workflows:
  android-build:
    name: Android Build
    max_build_duration: 30
    environment:
      flutter: 3.24.0
    scripts:
      - name: Setup Android project
        script: |
          cd android-source
          flutter create --platforms=android .
      - name: Build APK
        script: |
          cd android-source
          flutter pub get
          flutter build apk --release
    artifacts:
      - android-source/build/app/outputs/flutter-apk/app-release.apk

  ios-build:
    name: iOS Build
    max_build_duration: 30
    environment:
      flutter: 3.24.0
      xcode: 16.0
      cocoapods: default
    scripts:
      - name: Setup iOS project
        script: |
          cd ios-source
          flutter create --platforms=ios .
      - name: Build iOS
        script: |
          cd ios-source
          flutter pub get
          flutter build ios --release --no-codesign
    artifacts:
      - ios-source/build/ios/iphoneos/Runner.app